SetTutor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('setlanguage', views.setLanguage, name="setlanguage"),
    path('question', views.questionPage, name="questionPage"),
    path('createQuestion', views.createQuestionPage, name="createQuestionPage"),
    path('ajax/checkAnswer', views.checkAnswer, name="checkAnswer")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('SetTutor.urls')),
    path('admin/', admin.site.urls)
]

SetTutor/models.py
from django.db import models
import random

class QuestionsManager(models.Manager):
    def random(self):
        count = self.aggregate(ids=models.Count('id'))['ids']
        random_index = random.randint(0, count - 1)
        return self.all()[random_index]
    
class Questions(models.Model):
    Question = models.CharField(max_length=512)
    Difficulty = models.CharField(max_length=16)
    Type = models.IntegerField()

    objects = QuestionsManager()

SetTutor/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


DIFFICULTY_CHOICES = (
    ("Easy",_("Easy")),
    ("Medium",_("Medium")),
    ("Hard",_("Hard"))
)

TYPE_CHOICES = (
    (1,_("Simplify")),
    (2,_("Diagram"))
)

class QuestionForm(forms.Form):
    Question = forms.CharField(label=_('Question'), max_length=512)
    Difficulty = forms.ChoiceField(label=_("Difficulty"), choices=DIFFICULTY_CHOICES)
    Type = forms.ChoiceField(label=_("Type"), choices=TYPE_CHOICES,initial=2)

class AnswerFormReturned(forms.Form):
    Question = forms.CharField(max_length=128)
    Difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES)
    Type = forms.ChoiceField(choices=TYPE_CHOICES)
    Answer = forms.CharField(label='Answer', max_length=128)

class LanguageForm(forms.Form):
    Language = forms.CharField(max_length=5)
    next = forms.CharField(max_length=128)

SetTutor/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Questions
from .forms import QuestionForm, LanguageForm, AnswerFormReturned
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.utils import translation
from django import http
from django.conf import settings
from django_ajax.decorators import ajax
from SetClass import Set

SIMPLIFY_TYPE = 1
DIAGRAM_TYPE = 2

def homePage(request):
    template = loader.get_template('homepage.html')
    return HttpResponse(template.render({}, request))

def createQuestionPage(request):
  if request.method == 'POST':
    form = QuestionForm(request.POST)
    if form.is_valid():
      Q = form.cleaned_data["Question"].upper()
      D = form.cleaned_data["Difficulty"]
      T = form.cleaned_data["Type"]
      x = Set(D)

      if T == SIMPLIFY_TYPE:
        if not x.regionRegexCheck(Q):
          return HttpResponseRedirect('/')                
      elif T == DIAGRAM_TYPE:
        if not x.equationRegexCheck(Q) or not x.balancedParentheses(Q):
          return HttpResponseRedirect('/')     

      question = Questions(
          Question=Q,
          Difficulty=D,
          Type=T
      )
      question.save()

      return HttpResponseRedirect('/')
  else:
      form = QuestionForm()
  return render(request, 'CreateQuestion.html', {'form': form})

def questionPage(request):
  question = Questions.objects.random()
  template = loader.get_template('questionpage.html')
  context = {
    'Question': question.Question,
    'Difficulty': question.Difficulty,
    'Type':question.Type
  }
  return HttpResponse(template.render(context,request))

@ajax
def checkAnswer(request):
  if request.method == 'POST':
    form = AnswerFormReturned(request.POST)
    if form.is_valid():
      Question = form.cleaned_data["Question"]
      Difficulty = form.cleaned_data["Difficulty"]
      Type = int(form.cleaned_data["Type"])
      Answer = form.cleaned_data["Answer"].upper()

      if correctAnswer(Question,Difficulty,Type,Answer):
        return {"Result":True}

      return {"Result":False}
  return {"Error":""}


def setLanguage(request):
    if request.method == 'POST':
        form = LanguageForm(request.POST)
        if form.is_valid():
            language = form.cleaned_data["Language"]
            next = form.cleaned_data["next"]
            translation.activate(language)
            response = http.HttpResponseRedirect(next)
            response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
            return response
    return HttpResponseRedirect('/')

def correctAnswer(Question,Difficulty,Type,Answer):
  x = Set(Difficulty)
  if Type == SIMPLIFY_TYPE:
    if not x.equationRegexCheck(Answer) or not x.balancedParentheses(Answer):
       return False
    return x.evaluate(Answer) == eval(Question)
  elif Type == DIAGRAM_TYPE: 
    if not x.regionRegexCheck(Answer):
       return False
    return x.evaluate(Question) == eval(Answer)
  

SetTutor/templates/CreateQuestion.html
{% extends "master.html" %} {% load i18n%} {% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script>
    
  $(function () {/* DOM ready */ 
    
      var visibleVenn = "venn2";
      var notVisibleVenn = "venn3";
      canShadeVenn("venn2"); 
      canShadeVenn("venn3"); 

      function displayVenn(){
        $("#"+visibleVenn).css("display", "");
        $("#"+notVisibleVenn).css("display", "none");
      }

      $("#id_Type").change(function (e) {
      var selectVal = $("#id_Type option:selected").val();
      if (selectVal == "1") {

        $("#id_Question").css("display", "none");
        $("label[for=id_Question]").css("display", "none");
        //Show Correct Diagram
        displayVenn();
      } else {
        $("#id_Question").css("display", "");
        $("label[for=id_Question]").css("display", "");
        
        //Hide Diagrams
        $("#venn2").css("display", "none");
        $("#venn3").css("display", "none");
      }
    });

    $("#id_Difficulty").change(function (e) {
        if($("#id_Difficulty option:selected").val() == "Easy"){
            visibleVenn = "venn2";
            notVisibleVenn = "venn3";
        }else{
            visibleVenn = "venn3";
            notVisibleVenn = "venn2";
        }
        if($("#id_Type option:selected").val() == "1"){
          displayVenn();
        }
        console.log($("#id_Difficulty option:selected").val());

    });


  });

  function setAnswer() {
    //If Diagram then set Question Field to representative regions
    if ($("#id_Type").val() == 1) {
      $("#id_Question").val(getRegions());
    }
  }
</script>
{% endblock%} {% block body %}
<a href="/" id="home-btn">🏠{% trans "Home Page"%}</a>
<div id="create-question-container">
  <h1>Create a question</h1>
  <form
    id="questionform"
    action="createQuestion"
    method="post"
    onsubmit="setAnswer()"
    novalidate
  >
    {% csrf_token %} {{form}} <input id="create-question-submit" type="submit"
    value="{% trans "Submit" %}" />
  </form>

  <svg
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    version="1.1"
    width="440"
    height="320"
    id="venn2"
    style="display: none"
  >
    <defs id="defs4" />
    <g transform="translate(-120,-250)" id="layer1">
      <text x="150" y="550" font-family="Verdana" font-size="35" fill="blue">
        A
      </text>
      <text x="510" y="550" font-family="Verdana" font-size="35" fill="blue">
        B
      </text>
      <path
        d="m 406,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="A"
      />
      <path
        d="m 554,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="B"
      />
      <g class="overlap circle-top circle-left circle-right" id="AB">
        <path
          d="m 340,292.36218 c -39.62859,24.72433 -66,68.7254 -66,118.875 0,1.1766 0.002,2.3303 0.0312,3.5 19.65735,10.5221 42.11343,16.5 65.96875,16.5 23.85532,0 46.3114,-5.9779 65.96875,-16.5 0.0289,-1.1697 0.0312,-2.3234 0.0312,-3.5 0,-50.1496 -26.37141,-94.15067 -66,-118.875 z"
        />
        <path
          d="m 274,415.28198 c 1.19491,48.69086 27.26477,91.19629 65.96875,115.34375 38.70398,-24.14746 64.77384,-66.65289 65.96875,-115.34375"
        />
      </g>
    </g>
  </svg>

  <svg
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    version="1.1"
    width="440"
    height="410"
    id="venn3"
    style="display: none"
  >
    <text
      x="85"
      y="50"
      font-family="Verdana"
      font-size="35"
      fill="blue"
      text-anchor="middle"
    >
      B
    </text>
    <text x="20" y="390" font-family="Verdana" font-size="35" fill="blue">
      A
    </text>
    <text x="400" y="390" font-family="Verdana" font-size="35" fill="blue">
      C
    </text>
    <defs id="defs4" />
    <g transform="translate(-125.5,-151.86218)" id="layer1">
      <path
        d="m 480,292.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="B"
      />
      <path
        d="m 406,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="A"
      />
      <path
        d="m 554,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="C"
      />
      <path
        d="m 340,292.36218 c -39.62859,24.72433 -66,68.7254 -66,118.875 0,1.1766 0.002,2.3303 0.0312,3.5 19.65735,10.5221 42.11343,16.5 65.96875,16.5 23.85532,0 46.3114,-5.9779 65.96875,-16.5 0.0289,-1.1697 0.0312,-2.3234 0.0312,-3.5 0,-50.1496 -26.37141,-94.15067 -66,-118.875 z"
        class="overlap circle-top circle-left circle-right"
        id="ABC"
      />
      <path
        d="m 266.25003,271.46933 c -23.85532,0 -46.3114,5.94667 -65.96875,16.46875 -0.0289,1.16993 -0.0312,2.35437 -0.0312,3.53125 0,53.46323 29.97697,99.91736 74.03125,123.5 -0.0289,-1.16966 -0.0312,-2.32339 -0.0312,-3.5 0,-50.14004 26.35267,-94.14806 65.96875,-118.875 -21.46249,-13.38134 -46.81378,-21.125 -73.96875,-21.125 z"
        class="overlap circle-top circle-left"
        id="AB"
      />
      <path
        d="m 413.7005,271.90228 c 23.85532,0 46.3114,5.94667 65.96875,16.46875 0.0289,1.16993 0.0312,2.35437 0.0312,3.53125 0,53.46323 -29.97697,99.91736 -74.03125,123.5 0.0289,-1.16966 0.0312,-2.32339 0.0312,-3.5 0,-50.14004 -26.35267,-94.14806 -65.96875,-118.875 21.46249,-13.38134 46.81378,-21.125 73.96875,-21.125 z"
        class="overlap circle-right circle-top"
        id="BC"
      />
      <path
        d="m 274,415.28198 c 1.19491,48.69086 27.26477,91.19629 65.96875,115.34375 38.70398,-24.14746 64.77384,-66.65289 65.96875,-115.34375 -19.65735,10.52208 -42.11343,16.5 -65.96875,16.5 -23.85532,0 -46.3114,-5.97792 -65.96875,-16.5 z"
        class="overlap circle-right circle-left"
        id="AC"
      />
    </g>
  </svg>
</div>

{%endblock%}

SetTutor/templates/HomePage.html
{% extends "master.html" %} {% load i18n%} {% block body %}
<h1 id="title">Set Tutor</h1>
<div id="container">
  <div id="menu-button-container">
    <a href="" class="menu-button"><p>{% trans "Set Calculator" %}</p></a>
    <a href="question" class="menu-button"><p>{% trans "Questions" %}</p></a>
    <a href="createQuestion" class="menu-button"><p>{% trans "Create Questions" %}</p></a>
  </div>
</div>
{% endblock %}

SetTutor/templates/LanguageSelection.html
{% load i18n%}
<form action="setlanguage" method="post" id="select-language">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ request.path }}" />
    <select name="Language" id="language-dropdown">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Change" id="submit-language"/>
</form>

SetTutor/templates/master.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block head %}{% endblock %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SetTutor</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    {% include "LanguageSelection.html" %} {% block body %}{% endblock %}
    <script src="{% static 'venn.js' %}"></script>
  </body>
</html>

SetTutor/templates/questionpage.html
{% extends "master.html" %} {% load i18n %} {% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>

  $(function(){ /* DOM ready */

      var visibleVenn = "venn" + (2 + ("{{Difficulty}}" != "Easy"));
      if({{Type}} == 1){
          $("#id_Answer").css("display","");

          //Show Diagram Q
          $("#"+visibleVenn).css("display","");
          shadeRegions("{{Question}}",visibleVenn);

          $("#questiontext").html("{% trans "SimplifyPrompt" %}");
      }else{
          $("#id_Answer").css("display","none");
          $("#symbols").css("display","none");


          //Show Diagram (for user input)
          canShadeVenn(visibleVenn); 
          $("#"+visibleVenn).css("display","");

          $("#questiontext").html("{% trans "Shade" %} {{Question}} {% trans "on-Diagram" %}");
      }
  });

  function getAnswer(){
      //If Diagram then set Answer Field to representative regions
      if({{Type}} == 2){
          $("#id_Answer").val(getRegions());
      }
      return $("#answer-form").serialize();
  }

  function ajax(){
      $.ajax({
          type: 'POST',
          url: "ajax/checkAnswer",
          data: getAnswer(),
          success: function (response) {
              if(response.content.Result == true){
                $("#answer-form").css("display","none");
                $("#wrongtext").css("display","none")
                $("#correcttext").html("{% trans "Correct Answer" %}")
                $("#nextq").css("display","")
              }else{
                $("#wrongtext").html("{% trans "Wrong Answer" %}")
              }
          },
          error: function (response) {
              alert(response["responseJSON"]["error"]);
          }
      });
  }
</script>
{%endblock %} {% block body %}
<a href="/" id="home-btn">🏠{% trans "Home Page"%}</a>

<div id="questioncontainer">
  <h1 id="questiontitle">{%trans Difficulty %} {% trans "Question" %}</h1>
  <p id="questiontext"></p>

  <svg
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    version="1.1"
    width="440"
    height="320"
    id="venn2"
    style="display: none"
  >
    <defs id="defs4" />
    <g transform="translate(-120,-250)" id="layer1">
      <text x="150" y="550" font-family="Verdana" font-size="35" fill="blue">
        A
      </text>
      <text x="510" y="550" font-family="Verdana" font-size="35" fill="blue">
        B
      </text>
      <path
        d="m 406,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="A"
      />
      <path
        d="m 554,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="B"
      />
      <g class="overlap circle-top circle-left circle-right" id="AB">
        <path
          d="m 340,292.36218 c -39.62859,24.72433 -66,68.7254 -66,118.875 0,1.1766 0.002,2.3303 0.0312,3.5 19.65735,10.5221 42.11343,16.5 65.96875,16.5 23.85532,0 46.3114,-5.9779 65.96875,-16.5 0.0289,-1.1697 0.0312,-2.3234 0.0312,-3.5 0,-50.1496 -26.37141,-94.15067 -66,-118.875 z"
        />
        <path
          d="m 274,415.28198 c 1.19491,48.69086 27.26477,91.19629 65.96875,115.34375 38.70398,-24.14746 64.77384,-66.65289 65.96875,-115.34375"
        />
      </g>
    </g>
  </svg>

  <svg
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    version="1.1"
    width="440"
    height="410"
    id="venn3"
    style="display: none"
  >
    <text
      x="85"
      y="50"
      font-family="Verdana"
      font-size="35"
      fill="blue"
      text-anchor="middle"
    >
      B
    </text>
    <text x="20" y="390" font-family="Verdana" font-size="35" fill="blue">
      A
    </text>
    <text x="400" y="390" font-family="Verdana" font-size="35" fill="blue">
      C
    </text>
    <defs id="defs4" />
    <g transform="translate(-125.5,-151.86218)" id="layer1">
      <path
        d="m 480,292.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="B"
      />
      <path
        d="m 406,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="A"
      />
      <path
        d="m 554,412.36218 c 0,77.31987 -62.68014,140 -140,140 -77.31986,0 -140,-62.68013 -140,-140 0,-77.31986 62.68014,-140 140,-140 77.31986,0 140,62.68014 140,140 z"
        id="C"
      />
      <path
        d="m 340,292.36218 c -39.62859,24.72433 -66,68.7254 -66,118.875 0,1.1766 0.002,2.3303 0.0312,3.5 19.65735,10.5221 42.11343,16.5 65.96875,16.5 23.85532,0 46.3114,-5.9779 65.96875,-16.5 0.0289,-1.1697 0.0312,-2.3234 0.0312,-3.5 0,-50.1496 -26.37141,-94.15067 -66,-118.875 z"
        class="overlap circle-top circle-left circle-right"
        id="ABC"
      />
      <path
        d="m 266.25003,271.46933 c -23.85532,0 -46.3114,5.94667 -65.96875,16.46875 -0.0289,1.16993 -0.0312,2.35437 -0.0312,3.53125 0,53.46323 29.97697,99.91736 74.03125,123.5 -0.0289,-1.16966 -0.0312,-2.32339 -0.0312,-3.5 0,-50.14004 26.35267,-94.14806 65.96875,-118.875 -21.46249,-13.38134 -46.81378,-21.125 -73.96875,-21.125 z"
        class="overlap circle-top circle-left"
        id="AB"
      />
      <path
        d="m 413.7005,271.90228 c 23.85532,0 46.3114,5.94667 65.96875,16.46875 0.0289,1.16993 0.0312,2.35437 0.0312,3.53125 0,53.46323 -29.97697,99.91736 -74.03125,123.5 0.0289,-1.16966 0.0312,-2.32339 0.0312,-3.5 0,-50.14004 -26.35267,-94.14806 -65.96875,-118.875 21.46249,-13.38134 46.81378,-21.125 73.96875,-21.125 z"
        class="overlap circle-right circle-top"
        id="BC"
      />
      <path
        d="m 274,415.28198 c 1.19491,48.69086 27.26477,91.19629 65.96875,115.34375 38.70398,-24.14746 64.77384,-66.65289 65.96875,-115.34375 -19.65735,10.52208 -42.11343,16.5 -65.96875,16.5 -23.85532,0 -46.3114,-5.97792 -65.96875,-16.5 z"
        class="overlap circle-right circle-left"
        id="AC"
      />
    </g>
  </svg>

  <form id="answer-form" onsubmit="ajax();return false;">
    {% csrf_token %}
    <input type="hidden" value="{{Difficulty}}" name="Difficulty" />
    <input type="hidden" value="{{Question}}" name="Question" />
    <input type="hidden" value="{{Type}}" name="Type" />
    <input type="text" name="Answer" id="id_Answer" />
    <input type="submit" value="{% trans "Submit" %}" id="questionsubmit"/>
  </form>
  <div>
    <p id="correcttext"></p>
    <p id="wrongtext"></p>
    <button
      id="nextq"
      onclick="location.href='question';"
      style="display: none"
    >
      {% trans "Next Question" %}
    </button>
  </div>
  <div id="symbols">
    <button class="symbol-btn">∪</button>
    <button class="symbol-btn">∩</button>
    <button class="symbol-btn">Δ</button>
  </div>
</div>

{% endblock %}

<!-- d="m 274,415.28198 c 1.19491,48.69086 27.26477,91.19629 65.96875,115.34375 38.70398,-24.14746 64.77384,-66.65289 65.96875,-115.34375" -->